language: node_js

node_js:
  - "7"

addons:
  chrome: stable

install:
  - npm install
  - npm install -g codecov

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

after_success:
  - codecov --token=55be1d7a-820b-4d03-88fb-51061b4735f9

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always